openapi: 3.0.0 # OpenAPI-Version (erlaubte Features und Syntax)

info: # Allgemeine Infos zur Schnittstelle
  title: EDI@Energy API-Webdienst zur Reklamation von fehlenden Mengen auf Ebene Messlokation
  version: 1.0.0
  description: Mit diesem Web-Service können mehrere Mengen oder Lastgaänge auf Ebene der Messlokation zu verschiedenen 
    Zeitpunkten reklamiert werden. Die Wiederholung erfolgt innerhalb des arrays im Body. 
    Dies kann sowohl vom Messwerte-Hub beim MSB erfolgen, als auch von berechtigten Marktpartnern, 
    welche zum Zeitpunkt der Anfrage der Lokation zugeordnet sind, beim Messwerte-Hub. Die Anfrage erfolgt mittels der ID Der Messlokation. 
    Es ist zusätzlich verpflichtend die betroffene OBIS-Kennzahl anzugeben, welche für die Berechnung der Menge der Marktlokation notwendig ist. 
    Hinweis  wird von der Messlokation sowohl die ein Wert für den Bezug als auch für die Erzeugung benötigt, und beide fehlen, so ist die Reklamation je OBIS-Kennzahl einmal auszuführen. 
    Es ist das Zeitintervall  anzugeben, zu dem der WErt gemäß vereinbarung bereitgestellt werden sollte. 
      
servers: # URLs unter der die API bereitsteht
  - url: https://github.com/EDI-Energy/
    description: GitHub-Server der EDI@Energy.


paths:
  /meterLocation/amounts/complaint/v0.0.1:
    post:
      parameters:
        - name: transactionId
          in: header
          description: Externe Transaktions-Id zur eindeutigen Identifikation der Anfrage.
          required: true 
          style: simple
          explode: false
          schema:
            $ref: '../../../Schema/Header/transactionId.yaml#/components/schemas/transactionId'
        - name: creationDateTime
          in: header
          description: Zeitpunkt an dem der Aufruf erstellt wurde
          required: true
          style: simple
          explode: false
          schema:
            $ref: '../../../Schema/Header/creationDateTime.yaml#/components/schemas/creationDateTime'
        - name: initialTransactionId
          in: header
          description: Zur Angabe des Idempodenzschlüssel im Falle eines Retry.
          required: false
          style: simple
          explode: false
          schema:
            $ref: '../../../Schema/Header/initialTransactionId.yaml#/components/schemas/initialTransactionId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../../Schema/Werte/Werte_Reklamation/parameterMeasuredComplaintDatasMeterLocation.yaml#/components/schemas/parameterMeasuredComplaintDatasMeterLocation'
      responses:
        '202':
          description: accepted
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
