openapi: 3.0.0
info:
  title: EDI@Energy API-Webdienst zur Übermittlung der Kommunikationsdaten eines Lieferanten an einen Lieferanten
  version: 1.0.0
  description: Diese Schnittstelle nutzt ein Unternehmen in der Marktrolle Lieferant zur Übermittlung seiner Kommunikationsdaten an die Marktrollen LF
servers:
  - url: https://github.com/EDI-Energy/Konzept_API_Strom/blob/2025_08_01_Konsultation/API/Kommunikationsdatenblatt/KommunikationsdatenLFanLF.yaml
    description: GitHub-Server der EDI@Energy.
paths:
  /kommunikationsparameterLFanLF/v1:
    post:
      tags:
        - Kommunikationsparamter LF an LF
      summary: Austausch der Kommunikationsparameter zwischen Lieferant und Lieferant
      description: Austausch der Kommunikationsparameter zwischen Lieferant und Lieferant
      parameters:
        - name: transactionId
          in: header
          description: Externe Transaktions-Id zur eindeutigen Identifikation der Anfrage der MaLo-ID der Marktlokation des sendenden Marktpartners.
          required: true
          style: simple
          explode: false
          schema:
            $ref: '../../Schema/transactionId.yaml#/components/schemas/transactionId'
        - name: creationDateTime
          in: header
          description: Zeitpunkt, an dem der Aufruf erstellt wurde
          required: true
          style: simple
          explode: false
          schema:
            $ref: '../../Schema/creationDateTime.yaml#/components/schemas/creationDateTime'
        - name: initialTransactionId
          in: header
          description: Zur Angabe des Idempotenzschlüssels im Falle eines Retry.
          required: false
          style: simple
          explode: false
          schema:
            $ref: '../../Schema/initialTransactionId.yaml#/components/schemas/initialTransactionId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../../Schema/Kommunikationsdatenblatt/dataCommunicationDataSheetLFtoLF.yaml#/components/schemas/dataCommunicationDataSheetLFtoLF'
      responses:
        '202':
          description: accepted
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error