openapi: 3.0.0
info:
  title: EDI@Energy API-Webdienst zur Übermittlung der Kommunikationsdaten eines Lieferanten an einen Lieferanten
  version: 1.0.0
  description: Diese Schnittstelle nutzt ein Unternehmen in der Marktrolle Lieferant zur Übermittlung seiner Kommunikationsdaten an die Marktrollen LF
servers:
  - url: https://github.com/EDI-Energy/apis-demo/blob/main/api/kommunikationsparameterLFanLF.yaml
    description: GitHub-Server der EDI@Energy.
paths:
  /kommunikationsparameterLFanLF/v1:
    post:
      tags:
        - Kommunikationsparamter LF an LF
      summary: Austausch der Kommunikationsparameter zwischen Lieferant und Lieferant
      description: Austausch der Kommunikationsparameter zwischen Lieferant und Lieferant
      parameters:
        - name: transactionId
          in: header
          description: Externe Transaktions-Id zur eindeutigen Identifikation der Anfrage der MaLo-ID der Marktlokation des sendenden Marktpartners.
          required: true
          style: simple
          explode: false
          schema:
            $ref: '#/components/schemas/transactionId'
        - name: creationDateTime
          in: header
          description: Zeitpunkt, an dem der Aufruf erstellt wurde
          required: true
          style: simple
          explode: false
          schema:
            $ref: '#/components/schemas/creationDateTime'
        - name: initialTransactionId
          in: header
          description: Zur Angabe des Idempotenzschlüssels im Falle eines Retry.
          required: false
          style: simple
          explode: false
          schema:
            $ref: '#/components/schemas/initialTransactionId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dataCommunicationDataSheetLFtoLF'
      responses:
        '202':
          description: accepted
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '500':
          description: Internal Server Error
components:
  schemas:
    transactionId:
      type: string
      description: Externe Transaktionsnummer zur eindeutigen Identifikation des Vorgangs des sendenden Marktpartners
      format: UUID RFC4122
      example: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
    creationDateTime:
      pattern: 20(\d{2}(\-(0[13578]|1[02])\-(0[1-9]|[12]\d|3[01])|\-02\-(0[1-9]|1\d|2[0-8])|\-(0[469]|11)\-(0[1-9]|[12]\d|30))|([02468][048]|[13579][26])\-02\-(29))T([01]\d|2[0-3]):[0-5]\d:[0-5]\d(\.[\d]{1,4})?Z
      type: string
      description: Zeitpunkt an dem der Aufruf erstellt wurde
      example: '2023-08-01T12:30:00.1704Z'
    initialTransactionId:
      type: string
      description: Zur Angabe des Idempodenzschlüssel im Falle eines Retry.
      format: UUID RFC4122
      example: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
    company:
      type: string
      description: Angabe des Firmennamen
      example: BDEW & Co. KG
    countryCode:
      type: string
      pattern: '[A-Z]{2}'
      description: Angabe des Ländercodes nach ISO-3166-1 Alpha-2
      example: DE
    zipCode:
      type: string
      description: Angabe der Postleitzahl der Marktlokationsadresse
      example: 12117
    city:
      type: string
      description: Angabe des Ortes der Marktlokationsadresse
      example: Berlin
    street:
      type: string
      description: Angabe der Straße der Marktlokationsadresse
      example: Reinhardtstraße
    houseNumber:
      type: integer
      description: Angabe der Hausnummer der Marktlokationsadresse
      example: 32
    houseNumberAddition:
      type: string
      description: Angabe der Hausnummernergänzung der Marktlokationsadresse
      example: F
    address:
      type: object
      properties:
        countryCode:
          $ref: '#/components/schemas/countryCode'
        zipCode:
          $ref: '#/components/schemas/zipCode'
        city:
          $ref: '#/components/schemas/city'
        street:
          $ref: '#/components/schemas/street'
        houseNumber:
          $ref: '#/components/schemas/houseNumber'
        houseNumberAddition:
          $ref: '#/components/schemas/houseNumberAddition'
    dataBankDetails:
      type: array
      items:
        type: object
        properties:
          iban:
            type: string
            description: Internationale Bankkontonummer
            pattern: '[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}'
            example: DE89370400440532013000
          accountHolder:
            type: string
            description: Name des Kontoinhabers
            example: Stadtwerke XY
          bic:
            type: string
            description: Business Identifier Code (BIC)
            pattern: '[A-Z0-9]{8}([A-Z0-9]{3})?'
            example: DEUTDE61
          creditInstitution:
            type: string
            description: Name des Kreditinstituts
            example: Bank XY
        required:
          - iban
          - accountHolder
          - bic
          - creditInstitution
    dataContactPerson:
      type: array
      items:
        type: object
        properties:
          company:
            $ref: '#/components/schemas/company'
          address:
            description: Adresse des Unternehmens
            $ref: '#/components/schemas/address'
          department:
            type: string
            description: Name der organisatorischen Einheit
            example: Abteilung XY
          eMail:
            type: string
            description: E-Mailadresse des Ansprechpartners
            example: peter.mueller@stadtwerkxy.de
          phoneNumber:
            type: string
            description: Telefonnummer des Ansprechpartners
            example: 4912345678
        required:
          - company
          - address
          - department
          - eMail
          - phoneNumber
    dataCommunicationDataSheetLFtoLF:
      type: array
      description: Kommunikationsparameter, die zwischen den Marktrollen Lieferant (LF) und Lieferant (LF) auszutauschen sind.
      items:
        type: object
        properties:
          company:
            $ref: '#/components/schemas/company'
          address:
            description: Adresse des Unternehmens
            $ref: '#/components/schemas/address'
          dataBankDetails:
            description: Bankinformationen des Unternehmens
            $ref: '#/components/schemas/dataBankDetails'
          website:
            type: string
            description: Internetseite
            example: www.stadtwerkxy.de
          court:
            type: string
            description: Name des Gerichts
            example: Amtsgericht Moers
          commercialRegister:
            type: string
            description: Handelsregister-Nummer
            example: HRA 1234
          taxId:
            type: string
            description: Umsatzsteuernummer oder Steuernummer
            example: DE124356789
          faxNumber:
            type: string
            description: FAX-Nummer
            pattern: \+\\d{6,15}
            example: 494012345678
          availability:
            type: string
            description: Erreichbarkeit des Unternehmens
            pattern: Verfügbarkeit Montag \d{2}:\d{2} bis \d{2}:\d{2} Uhr, Verfügbarkeit Dienstag \d{2}:\d{2} bis \d{2}:\d{2} Uhr, Verfügbarkeit Mittwoch \d{2}:\d{2} bis \d{2}:\d{2} Uhr, Verfügbarkeit Donnerstag \d{2}:\d{2} bis \d{2}:\d{2} Uhr, Verfügbarkeit Freitag \d{2}:\d{2} bis \d{2}:\d{2} Uhr, Mittagspause \d{2}:\d{2} bis \d{2}:\d{2} Uhr
            example: Verfügbarkeit Donnerstag 08:00 bis 17:00 Uhr, Verfügbarkeit Freitag 08:00 bis 16:00 Uhr, Mittagspause 12:00 bis 13:00 Uhr"
          dataContactPersonDataExchange:
            description: Name und Anschrift des Ansprechpartners und Informationen zum Übertragungsweg/Datenaustausch
            $ref: '#/components/schemas/dataContactPerson'
          dataContactPersonFrameworkAgreements:
            description: Name und Anschrift des Ansprechpartners und Informationen zu Rahmenverträgen
            $ref: '#/components/schemas/dataContactPerson'
          dataContactPersonCancellationProcess:
            description: Name und Anschrift des Ansprechpartners und Informationen zu Kündigungsprozessen
            $ref: '#/components/schemas/dataContactPerson'
          dataContactPersonSwitchingProcess:
            description: Name und Anschrift des Ansprechpartners und Informationen zu Wechselprozessen
            $ref: '#/components/schemas/dataContactPerson'
          dataContactPersonMasterDataProcess:
            description: Name und Anschrift des Ansprechpartners und Informationen zu Stammdatenprozessen
            $ref: '#/components/schemas/dataContactPerson'
          dataContactPersonInputProcess:
            description: Name und Anschrift des Ansprechpartners und Informationen zu Einspeiseprozessen
            $ref: '#/components/schemas/dataContactPerson'
          dataContactPersonBillingProcess:
            description: Name und Anschrift des Ansprechpartners und Informationen zu Abrechnungsprozessen
            $ref: '#/components/schemas/dataContactPerson'
          dataContactPersonMMMAProcess:
            description: Name und Anschrift des Ansprechpartners und Informationen zu MMMA-Prozessen
            $ref: '#/components/schemas/dataContactPerson'
          dataContactPersonTransactionData:
            description: Name und Anschrift des Ansprechpartners und Informationen zu Bewegungsdaten
            $ref: '#/components/schemas/dataContactPerson'
          dataContactPersonInterruptionRestorationConnectionUsageProcess:
            description: Name und Anschrift des Ansprechpartners und Informationen zu Prozessen zur Unterbrechung und Wiederherstellung derAnschlussnutzung
            $ref: '#/components/schemas/dataContactPerson'
          dataContactPersonBalancingProcess:
            description: Name und Anschrift des Ansprechpartners und Informationen zu BilanzierungsprozesseN / Bilanzkreismanagement
            $ref: '#/components/schemas/dataContactPerson'
      required:
        - company
        - address
        - dataBankDetails
        - website
        - court
        - commercialRegister
        - taxId
        - faxNumber
        - availability
        - dataContactPersonDataExchange
        - dataContactPersonFrameworkAgreements
        - dataContactPersonCancellationProcess
        - dataContactPersonSwitchingProcess
        - dataContactPersonMasterDataProcess
        - dataContactPersonInputProcess
        - dataContactPersonBillingProcess
        - dataContactPersonMMMAProcess
        - dataContactPersonTransactionData
        - dataContactPersonInterruptionRestorationConnectionUsageProcess
        - dataContactPersonBalancingProcess
