openapi: 3.0.0
info:
  title: EDI@Energy API-Webdienst zur Übermittlung der Kündigungsnachrichten zwischen zwei Lieferanten
  version: v1.0.0
  description: Diese Schnittstelle nutzen zwei Lieferanten zur Übermittlung der Nachrichten für den GPKE-Prozess der Kündigung.
tags:
  - name: Kündigungsanfrage
    description: Find out more
    
paths:
  /terminationRequest/v1:
    post: 
      tags: 
       - Kündigungsanfrage
      description: 'Dieser POST wird aufgerufen, wenn ein LF eine Kündigungsanfrage an einen weiteren LF senden möchte'
      summary: Kündigungsanfrage
      parameters:
        - name: transactionId
          in: header
          description: Externe Transaktions-Id zur eindeutigen Identifikation der Übermittlung der Kommunikationsdaten.
          required: true
          style: simple 
          explode: false
          schema: 
            $ref: '../../schema/transactionId.yaml#/components/schemas/transactionId'
        - name: creationDateTime
          in: header
          description: Zeitpunkt an dem der Aufruf erstellt wurde
          required: true
          style: simple
          explode: false
          schema:
            $ref: '../../schema/creationDateTime.yaml#/components/schemas/creationDateTime'
        - name: initialTransactionId
          in: header
          description: Zur Angabe des Idempodenzschluessel im Falle eines Retry.
          required: false
          style: simple
          explode: false
          schema:
            $ref: '../../schema/initialTransactionId.yaml#/components/schemas/initialTransactionId'
      requestBody:
        content:
         application/json:
           schema:
             $ref: '../../schema/Wechselprozesse_GPKE/terminationDetails.yaml#/components/schemas/terminationDetails'
      responses:
        "202":
          description: accepted
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "405":
          description: Method not allowed
        "500":
          description: Internal Server Error