openapi: 3.0.0
info:
  title: EDI@Energy API-Webdienst zur Übermittlung von Messwerten
  version: 1.0.0
  description: Diese Schnittstelle nutzen Marktpartner zur Übermittlung von Messwerten im Rahmen der GPKE.
tags:
  - name: Messwertübermittlung
    description: Find out more
servers:
  - url: https://github.com/EDI-Energy
    description: GitHub-Server der EDI@Energy

paths:
  /meterReadingTransmission/v1:
    post:
      tags:
       - Messwertübermittlung
      description: 'Dieser POST wird aufgerufen, um Messwerte für eine oder mehrere Marktlokationen zu übermitteln.'
      summary: Messwertübermittlung
      parameters:
        - name: transactionId
          in: header
          description: Externe Transaktions-Id zur eindeutigen Identifikation der Übermittlung der Messwerte.
          required: true
          style: simple
          explode: false
          schema:
            $ref: '../../Schema/Header/transactionId.yaml#/components/schemas/transactionId'
        - name: creationDateTime
          in: header
          description: Zeitpunkt an dem der Aufruf erstellt wurde
          required: true
          style: simple
          explode: false
          schema:
            $ref: '../../Schema/Header/creationDateTime.yaml#/components/schemas/creationDateTime'
        - name: initialTransactionId
          in: header
          description: Zur Angabe des Idempodenzschluessel im Falle eines Retry.
          required: false
          style: simple
          explode: false
          schema:
            $ref: '../../Schema/Header/initialTransactionId.yaml#/components/schemas/initialTransactionId'
      requestBody:
        content:
         application/json:
           schema:
             $ref: '../../Schema/Wechselprozesse_GPKE/meterReadingTransmission.yaml#/components/schemas/meterReadingTransmission'
      responses:
        "202":
          description: accepted
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "405":
          description: Method not allowed
        "500":
          description: Internal Server Error
