name: Label Konsultation 01.08.2025

on:
  workflow_dispatch:

permissions:
  issues: write

env:
  # Secret mit erlaubten Nutzernamen (kommagetrennt oder zeilenweise)
  FREIGEGEBENE_NUTZERNAMEN: ${{ secrets.FREIGEGEBENE_NUTZERNAMEN }}

jobs:
  add_consultation_label:
    runs-on: ubuntu-latest
    steps:
      - name: Label vergeben (Konsultation 01.08.2025)
        uses: actions/github-script@v6
        with:
          script: |
            // Zeitraum festlegen
            const periodStart = new Date('2025-07-01T00:00:00Z');
            const periodEnd   = new Date('2025-08-01T00:00:00Z');

            // Secret einlesen und in Kleinbuchstaben umwandeln
            const rawSecret = process.env.FREIGEGEBENE_NUTZERNAMEN || '';
            const allowedUsers = rawSecret
              .split(/[\r\n,]+/)            // Komma oder Zeilenumbruch
              .map(u => u.trim().toLowerCase()) // trim + lowercase
              .filter(u => u);

            // Alle offenen Issues seit periodStart (paginiert) abfragen
            let allIssues = [];
            let page = 1;
            while (true) {
              const resp = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                since: periodStart.toISOString(),
                per_page: 100,
                page
              });
              if (resp.data.length === 0) break;
              allIssues = allIssues.concat(resp.data);
              page++;
            }

            // Jedes Issue prüfen und ggf. labeln
            for (const issue of allIssues) {
              const created = new Date(issue.created_at);
              // nur im Zeitraum und ohne existierende Labels
              if (
                created < periodStart ||
                created >= periodEnd ||
                issue.labels.length > 0
              ) continue;

              // Case-insensitive Username-Vergleich
              const user = issue.user.login.toLowerCase();
              const labelToAdd = allowedUsers.includes(user)
                ? 'Konsultation_01.08.2025'
                : 'Status zu klären';

              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: [labelToAdd]
              });
              console.log(`Issue #${issue.number}: Label "${labelToAdd}" vergeben (erstellt von ${issue.user.login}).`);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
