name: Label Konsultation 01.08.2025

on:
  workflow_dispatch:

permissions:
  issues: write

env:
  # Secret mit erlaubten Nutzernamen (Müssen kommagetrennt oder mit Zeilenumbruch und ohne Leerzeichen angelegt werden)
  FREIGEGEBENE_NUTZERNAMEN: ${{ secrets.FREIGEGEBENE_NUTZERNAMEN }}

jobs:
  add_consultation_label:
    runs-on: ubuntu-latest
    steps:
      - name: Label vergeben (Konsultation 01.08.2025)
        uses: actions/github-script@v6
        with:
          script: |
            const periodStart = new Date('2025-07-01T00:00:00Z');
            const periodEnd   = new Date('2025-08-01T00:00:00Z');

            const rawSecret = process.env.FREIGEGEBENE_NUTZERNAMEN || '';
            const allowedUsers = rawSecret
              .split(/[\r\n,]+/)            
              .map(u => u.trim().toLowerCase())
              .filter(u => u);

            let allIssues = [];
            let page = 1;
            while (true) {
              const resp = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                since: periodStart.toISOString(),
                per_page: 100,
                page
              });
              if (resp.data.length === 0) break;
              allIssues = allIssues.concat(resp.data);
              page++;
            }

            for (const issue of allIssues) {
              const created = new Date(issue.created_at);
              if (
                created < periodStart ||
                created >= periodEnd ||
                issue.labels.length > 0
              ) continue;

              const user = issue.user.login.toLowerCase();
              const labelToAdd = allowedUsers.includes(user)
                ? 'Konsultation_2025_08'
                : 'Status zu klären';

              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: [labelToAdd]
              })
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}